name: Load Versions
description: >
  Load version numbers from centralized config file
  (.github/config/versions.yaml)

outputs:
  rust-stable:
    description: "Rust stable version"
    value: ${{ steps.load.outputs.rust-stable }}
  rust-beta:
    description: "Rust beta version"
    value: ${{ steps.load.outputs.rust-beta }}
  rust-nightly:
    description: "Rust nightly version"
    value: ${{ steps.load.outputs.rust-nightly }}
  ocaml-version:
    description: "OCaml version"
    value: ${{ steps.load.outputs.ocaml-version }}
  node-version:
    description: "Node.js version"
    value: ${{ steps.load.outputs.node-version }}

runs:
  using: composite
  steps:
    - name: Load version configuration
      id: load
      shell: bash
      run: |
        VERSIONS_FILE="${GITHUB_WORKSPACE}/.github/config/versions.yaml"

        RUST_STABLE=$(yq eval '.rust.stable' "$VERSIONS_FILE")
        RUST_BETA=$(yq eval '.rust.beta' "$VERSIONS_FILE")
        RUST_NIGHTLY=$(yq eval '.rust.nightly' "$VERSIONS_FILE")
        OCAML_VERSION=$(yq eval '.ocaml.version' "$VERSIONS_FILE")
        NODE_VERSION=$(yq eval '.node.version' "$VERSIONS_FILE")

        echo "rust-stable=$RUST_STABLE" >> "$GITHUB_OUTPUT"
        echo "rust-beta=$RUST_BETA" >> "$GITHUB_OUTPUT"
        echo "rust-nightly=$RUST_NIGHTLY" >> "$GITHUB_OUTPUT"
        echo "ocaml-version=$OCAML_VERSION" >> "$GITHUB_OUTPUT"
        echo "node-version=$NODE_VERSION" >> "$GITHUB_OUTPUT"

        echo "Loaded versions:"
        echo "  Rust stable: $RUST_STABLE"
        echo "  Rust beta: $RUST_BETA"
        echo "  Rust nightly: $RUST_NIGHTLY"
        echo "  OCaml: $OCAML_VERSION"
        echo "  Node.js: $NODE_VERSION"
