[licenses]
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "CDLA-Permissive-2.0",
  "CC0-1.0",
  "ISC",
  "MIT",
  "Unlicensed",
  "Unicode-DFS-2016",
  "Unicode-3.0",
  "Zlib",
]