var N = null;var sourcesIndex = {};
sourcesIndex["commitment_dlog"] = {"name":"","files":["combine.rs","commitment.rs","lib.rs","qnr_field.rs","srs.rs"]};
sourcesIndex["groupmap"] = {"name":"","files":["lib.rs"]};
sourcesIndex["mina_curves"] = {"name":"","dirs":[{"name":"pasta","dirs":[{"name":"curves","files":["mod.rs","pallas.rs","vesta.rs"]},{"name":"fields","files":["fp.rs","fq.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["oracle"] = {"name":"","dirs":[{"name":"pasta","files":["fp.rs","fp5.rs","fp_3.rs","fq.rs","fq5.rs","fq_3.rs","mod.rs"]}],"files":["lib.rs","poseidon.rs","rndoracle.rs","sponge.rs","utils.rs"]};
sourcesIndex["plonk_5_wires_circuits"] = {"name":"","dirs":[{"name":"gates","files":["addition.rs","double.rs","endosclmul.rs","generic.rs","mod.rs","packing.rs","poseidon.rs","varbasemul.rs","varbasemulpck.rs"]},{"name":"polynomials","files":["addition.rs","double.rs","endosclmul.rs","generic.rs","mod.rs","packing.rs","permutation.rs","poseidon.rs","varbasemul.rs","varbasemulpck.rs"]}],"files":["constraints.rs","domains.rs","gate.rs","lib.rs","polynomial.rs","scalars.rs","wires.rs"]};
sourcesIndex["plonk_5_wires_protocol_dlog"] = {"name":"","files":["index.rs","lib.rs","plonk_sponge.rs","prover.rs","range.rs","verifier.rs"]};
sourcesIndex["plonk_circuits"] = {"name":"","dirs":[{"name":"gates","files":["addition.rs","endosclmul.rs","generic.rs","mod.rs","poseidon.rs","varbasemul.rs"]},{"name":"polynomials","files":["addition.rs","endosclmul.rs","generic.rs","mod.rs","permutation.rs","poseidon.rs","varbasemul.rs"]}],"files":["constraints.rs","domains.rs","gate.rs","lib.rs","polynomial.rs","scalars.rs","wires.rs"]};
sourcesIndex["plonk_protocol_dlog"] = {"name":"","files":["index.rs","lib.rs","plonk_sponge.rs","prover.rs","range.rs","verifier.rs"]};
createSourceSidebar();
