var N = null;var sourcesIndex = {};
sourcesIndex["commitment_dlog"] = {"name":"","files":["chunked.rs","combine.rs","commitment.rs","lib.rs","qnr_field.rs","srs.rs"]};
sourcesIndex["export_test_vectors"] = {"name":"","files":["export_test_vectors.rs","vectors.rs"]};
sourcesIndex["groupmap"] = {"name":"","files":["lib.rs"]};
sourcesIndex["kimchi"] = {"name":"","files":["index.rs","lib.rs","plonk_sponge.rs","prover.rs","range.rs","verifier.rs"]};
sourcesIndex["kimchi_circuits"] = {"name":"","dirs":[{"name":"gates","files":["endosclmul.rs","generic.rs","mod.rs","poseidon.rs","varbasemul.rs"]},{"name":"nolookup","files":["constraints.rs","mod.rs","scalars.rs"]},{"name":"polynomials","files":["chacha.rs","complete_add.rs","endomul_scalar.rs","endosclmul.rs","generic.rs","lookup.rs","mod.rs","permutation.rs","poseidon.rs","varbasemul.rs"]}],"files":["domains.rs","expr.rs","gate.rs","lib.rs","macros.rs","polynomial.rs","wires.rs"]};
sourcesIndex["mina_curves"] = {"name":"","dirs":[{"name":"pasta","dirs":[{"name":"curves","files":["mod.rs","pallas.rs","vesta.rs"]},{"name":"fields","files":["fp.rs","fq.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["lib.rs"]};
sourcesIndex["o1_utils"] = {"name":"","files":["dense_polynomial.rs","evaluations.rs","lib.rs","serialization.rs"]};
sourcesIndex["ocaml_derive"] = {"name":"","files":["lib.rs"]};
sourcesIndex["ocaml_gen"] = {"name":"","files":["conv.rs","lib.rs"]};
sourcesIndex["oracle"] = {"name":"","dirs":[{"name":"pasta","files":["fp.rs","fp5.rs","fp_3.rs","fq.rs","fq5.rs","fq_3.rs","mod.rs"]}],"files":["lib.rs","poseidon.rs","rndoracle.rs","sponge.rs"]};
sourcesIndex["plonk_circuits"] = {"name":"","dirs":[{"name":"gates","files":["addition.rs","endosclmul.rs","generic.rs","mod.rs","poseidon.rs","varbasemul.rs"]},{"name":"polynomials","files":["addition.rs","endosclmul.rs","generic.rs","mod.rs","permutation.rs","poseidon.rs","varbasemul.rs"]}],"files":["constraints.rs","domains.rs","gate.rs","lib.rs","polynomial.rs","scalars.rs","wires.rs"]};
sourcesIndex["plonk_protocol_dlog"] = {"name":"","files":["index.rs","lib.rs","plonk_sponge.rs","prover.rs","range.rs","verifier.rs"]};
createSourceSidebar();
