include = ["**/Cargo.toml"]
exclude = ["o1vm/ethereum-optimism/**"]

[formatting]
reorder_keys = true

[[rule]]
include = ["**/Cargo.toml"]
keys = ["dependencies", "workspace.dependencies"]
formatting = { reorder_keys = true }
