[package]
name = "plonk_15_wires_protocol_dlog"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-serialize = "0.3.0"
array-init = "1.0.0"
bincode = "1.3.3"
colored = "2.0.0"
rand = "0.8.0"
rand_core = { version = "0.5" }
rayon = "1.5.0"
serde = "1.0.130"
serde_with = "1.10.0"
sprs = "0.9.2"

ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { path = "../../ocaml-gen", optional = true}

commitment_dlog = { path = "../commitment" }
o1-utils = { path = "../../utils" }
oracle = { path = "../../oracle" }
plonk_15_wires_circuits = { path = "../../circuits/plonk-15-wires" }

[dev-dependencies]
groupmap = { path = "../../groupmap" }
mina-curves = { path = "../../curves" }
bincode = "1.3.3"

[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen", "plonk_15_wires_circuits/ocaml_types", "commitment_dlog/ocaml_types" ]
