[package]
name = "oracle"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
o1-utils = { path = "../utils" }
rand = "0.8.0"
rayon = { version = "1" }
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"

mina-curves = { path = "../curves" }

# for ocaml
ocaml = { version = "0.22.1", optional = true }
ocaml-gen = { path = "../ocaml-gen", optional = true }
syn = { version = "1.0.76", optional = true }

# for export_test_vectors
num-bigint = { version = "0.4.0" }
serde_json = { version = "1.0" }
hex = { version = "0.4" }
ark-serialize = "0.3.0"

[dev-dependencies]
hex = { version = "0.4" }

[features]
ocaml_types = [ "ocaml", "ocaml-gen", "syn" ]

# for test vectors
default = ["3w"]
3w = [ ]
5w = [ ]
3 = [ ]

[[bin]]
name = "export_test_vectors"
test = false
bench = false
path = "tests/export_test_vectors/export_test_vectors.rs"
