name: "Shared OCaml setting up steps"
description: "Shared OCaml setting up steps"
inputs:
  ocaml_version:
    description: "OCaml version"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup OCaml ${{ inputs.ocaml_version }}
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ inputs.ocaml_version }}
