name: "Shared Rust toolchain setting up steps"
description: "Shared Rust toolchain setting up steps"
inputs:
  cache:
    description: "to cache or not to cache, that is the question"
    required: false
    default: "true"
  rust_toolchain_version:
    description: "Rust toolchain version"
    required: true
  targets:
    description: "pass targets to the rust-toolchain installer"
    required: false
  components:
    description: "additional components"
    default: clippy, rustfmt
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # overwriting default rust-toolchain
        cat > rust-toolchain.toml << EOF
        [toolchain]
        channel = "${{ inputs.rust_toolchain_version }}"
        EOF
    - uses: dtolnay/rust-toolchain@master
      id: toolchain
      with:
        toolchain: ${{ inputs.rust_toolchain_version }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
    - if: ${{ inputs.cache == 'true' && inputs.targets != '' }}
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ steps.toolchain.outputs.cachekey }}-${{ inputs.targets }}
        # Some libraries are not often updated.
        cache-workspace-crates: true
    - if: ${{ inputs.cache == 'true' && inputs.targets == '' }}
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: ${{ steps.toolchain.outputs.cachekey }}-native
