[package]
name = "plonk_wasm"
version = "0.1.0"
authors = ["opensource@o1labs.org"]
description = "WASM stubs for plonk proof systems"
repository = "https://github.com/MinaProtocol/mina"
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "plonk_wasm"
crate-type = ["cdylib"]

################################# Dependencies ################################

[dependencies]
base64 = "0.13.0"
console_error_panic_hook = { version = "0.1.6" }
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3"
libc = "0.2.62"
num-bigint = { version = "0.4.0" }
once_cell = "1.10.0"
paste = "1.0.5"
rand = { version = "0.8.0" }
rayon = { version = "1" }
rmp-serde = "1.0.0"
spmc = { version = "0.3.0" }
serde = "1.0.171"
serde_json = "1.0.103"
serde_with = ">=2.1.0"
serde-wasm-bindgen = ">=0.4"
wasm-bindgen = { version = "=0.2.89" }
web-sys = { version = "0.3.35", features = [
  "Window",
  "Document",
  "HtmlElement",
  "Text",
  "Node",
  "Element",
] }

# arkworks
ark-ec = { workspace = true, features = ["parallel"] }
ark-ff = { workspace = true, features = ["parallel", "asm"] }
ark-poly = { workspace = true, features = ["parallel"] }
ark-serialize.workspace = true

# proof-systems
arkworks.workspace = true
groupmap.workspace = true
kimchi = { workspace = true, features = ["wasm_types"] }
mina-curves = { workspace = true }
mina-poseidon = { workspace = true }
o1-utils = { workspace = true }
poly-commitment = { workspace = true }
wasm-types.workspace = true

[dev-dependencies]
wasm-bindgen-test.workspace = true

[features]
nodejs = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
#wasm-opt = ["-O4", "--detect-features", "--enable-mutable-globals" ]
#wasm-opt = ["-O4", "--enable-mutable-globals"]
