[package]
authors = ["opensource@o1labs.org"]
description = "WASM stubs for plonk proof systems"
edition = "2018"
license = "MIT/Apache-2.0"
name = "plonk_wasm"
repository = "https://github.com/MinaProtocol/mina"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]
name = "plonk_wasm"

################################# Dependencies ################################

[dependencies]
base64.workspace = true
console_error_panic_hook.workspace = true
getrandom = { workspace = true, features = ["js"] }
js-sys.workspace = true
libc.workspace = true
num-bigint.workspace = true
once_cell.workspace = true
paste.workspace = true
rand.workspace = true
rayon.workspace = true
rmp-serde.workspace = true
serde.workspace = true
serde-wasm-bindgen.workspace = true
serde_json.workspace = true
serde_with.workspace = true
spmc.workspace = true
# Strictly enforcing 0.2.87
wasm-bindgen.workspace = true
web-sys = { workspace = true, features = [
  "Window",
  "Document",
  "HtmlElement",
  "Text",
  "Node",
  "Element",
] }

# arkworks
ark-ec = { workspace = true, features = ["parallel"] }
ark-ff = { workspace = true, features = ["parallel", "asm"] }
ark-poly = { workspace = true, features = ["parallel"] }
ark-serialize.workspace = true

# proof-systems
groupmap.workspace = true
kimchi = { workspace = true, features = ["wasm_types"] }
mina-curves = { workspace = true }
mina-poseidon = { workspace = true }
o1-utils = { workspace = true }
poly-commitment = { workspace = true }

[dev-dependencies]
wasm-bindgen-test.workspace = true

[features]
nodejs = []

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
#wasm-opt = ["-O4", "--detect-features", "--enable-mutable-globals" ]
#wasm-opt = ["-O4", "--enable-mutable-globals"]
