name: 'Cache SRS Data'
description: 'Cache and generate SRS data if needed'

runs:
  using: "composite"
  steps:
    - name: Cache SRS data
      id: cache-srs
      uses: actions/cache@v3
      with:
        path: ./srs
        # The SRS generation never changes, so we don't need a content-based key
        key: srs-cache-key
    - name: Generate and Cache SRS
      if: steps.cache-srs.outputs.cache-hit != 'true'
      shell: bash
      run: cargo test -p kimchi heavy_test_srs_serialization --release