name: License Check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  license-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust and cargo deny
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.85.0
        run: cargo install cargo-deny

      - name: Run cargo-deny
        run: cargo deny check licenses
