name: Markdown Lint

on:
  push:
  pull_request:

jobs:
  readme-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Lint README
        run: markdownlint README.md
